language: java
sudo: false
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8
before_install:
- . ./build/before_install.sh

install:
- ./build/install.sh

script:
- ./build/build.sh

after_success:
- ./build/after_success.sh

notifications:
  slack:
    secure: INiA7V4aXvimkImaErVH94ZSmFNuOgun9aurmf3BiE2Qq0EfNiEaWK9pp6hfkv+wSls4LXNDLaYVzdoMECVLh+Dv9VLHIABnaNEmMStXUlyZ+sOpdayl/47gnNr0G1cr06eqbikGVqWtQaxDz2Psaejq2D/6WYw5Vnqk4BjWQHw=
